.builddocker: &builddocker |
    export CONTAINER_BASE=$CI_REGISTRY_IMAGE
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA .
    docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest
    docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
    docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest
    for CUSTOM in $(ls Dockerfile\.* | cut -d"." -f2)
    do
        docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CUSTOM:$CI_COMMIT_SHORT_SHA . -f Dockerfile.$CUSTOM
        docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CUSTOM:$CI_COMMIT_SHORT_SHA
        docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CUSTOM:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CUSTOM:latest 
        docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CUSTOM:latest
    done

stages:
    - docker

docker:
    stage: docker
    image: docker:latest
    tags:
        - shell
    script:
      - *builddocker