version: '3'

services:
  mem0-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MEM0_API_KEY=${MEM0_API_KEY}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped